[package]
name = "atmega328p-rs"
authors = ["Kestrel"]
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atmega = { path = "./src/atmega"}
